const gC = document.getElementById("gameCanvas")
const w = window.innerWidth
const h = window.innerHeight
const woh = w>h
const s = (woh)? h : w
const m = Math.abs(w - h) / 2
const gs = 1920
gC.height = gs
gC.width = gs
gC.style.boxSizing = "border-box";
const setS = "100v" + ((woh)? "h" : "w")
gC.style.height = setS
gC.style.width = setS